## @file    Makefile
## @brief   Build system for Red Pitaya FPGA projects targeting Xilinx Zynq-7000.
##
## @details This Makefile orchestrates the complete build pipeline from RTL
##          sources to a bootable SD card image. It handles FPGA synthesis and
##          implementation via Vivado, FSBL generation via XSCT, Linux kernel
##          and initramfs compilation, per-project device tree compilation, and
##          boot image assembly (FSBL + U-Boot) with uEnv.txt for flexible boot
##          configuration without recompiling boot.bin on every DTB change.
##
##          Each project gets its own output directory under tmp/<NAME>/ so
##          multiple projects can coexist without overwriting each other.
##
## @par Directory layout after a full build:
## @code
##   .
##   ├── zImage.bin                   (shared kernel, same for all projects)
##   ├── initrd.bin                   (shared Alpine initramfs, same for all)
##   ├── dts/
##   │   ├── uEnv-rootfs.txt          (source: U-Boot env for ext4 boot)
##   │   ├── uEnv-initrd.txt          (source: U-Boot env for initrd boot)
##   │   ├── rootfs.dts
##   │   ├── initrd.dts
##   │   └── common.dts
##   └── tmp/
##       ├── linux-6.12/              (kernel source, extracted from tarball)
##       ├── rtl8188eu-main.tar.gz    (WiFi driver tarball)
##       ├── device-tree-xlnx-*/      (Xilinx DT generator, extracted)
##       ├── u-boot.elf               (must be provided manually, see below)
##       ├── <NAME>.xpr               (Vivado project file)
##       ├── <NAME>.bit               (FPGA bitstream)
##       ├── <NAME>.xsa               (hardware description exported by Vivado)
##       ├── <NAME>.fsbl/             (First Stage Bootloader build artifacts)
##       ├── <NAME>.tree/             (device tree sources generated by XSCT)
##       └── <NAME>/                  (per-project final outputs)
##           ├── boot.bin             (FSBL + U-Boot; rarely needs rebuild)
##           ├── boot.bif             (bootgen input script, intermediate)
##           ├── boot-rootfs.bin      (legacy: FSBL + U-Boot + DTB, for os-image)
##           ├── rootfs.dtb           (DTB for ext4 root filesystem boot)
##           ├── initrd.dtb           (DTB for Alpine initrd boot)
##           ├── uEnv-rootfs.txt      (copy of dts/uEnv-rootfs.txt)
##           └── uEnv-initrd.txt      (copy of dts/uEnv-initrd.txt)
## @endcode
##
## @par Boot sequence overview:
## @code
##   Power on
##     └─> Zynq ROM loads boot.bin from SD FAT partition
##               └─> FSBL  -- initializes DDR, PLLs, MIO pads
##                     └─> U-Boot  -- mounts FAT, reads uEnv.txt
##                           ├── fatload  rootfs.dtb  -> RAM 0x2000000
##                           ├── fatload  zImage.bin  -> RAM 0x2008000
##                           └── bootz    0x2008000 - 0x2000000
##
##   Key insight: boot.bin contains only FSBL + U-Boot. The kernel and DTB
##   are plain files on the FAT partition, loaded by U-Boot at runtime.
##   A DTB change only requires copying a new .dtb to the SD card.
## @endcode
##
## @par Required external file (not downloaded automatically):
## @code
##   tmp/u-boot.elf  -- U-Boot binary compiled for Zynq-7000.
##                      Build from https://github.com/Xilinx/u-boot-xlnx
##                      using zynq_red_pitaya_defconfig, or copy a pre-built
##                      binary from your BSP into this exact path.
## @endcode
##
## @par Typical workflows:
## @code
##   Full project build:
##     make NAME=led_blinker all
##
##   Bitstream only (iterating on RTL, no need to rebuild kernel):
##     make NAME=led_blinker bit
##
##   Recompile only the device tree (fast, no Vivado invoked):
##     make NAME=led_blinker dtb
##
##   Show which files to copy to the SD FAT partition:
##     make NAME=led_blinker sd-rootfs
##     make NAME=led_blinker sd-initrd
##
##   Build a Debian root filesystem disk image (independent of 'all'):
##     make NAME=led_blinker os-image
##
##   Remove all generated files:
##     make clean
## @endcode

# -----------------------------------------------------------------------------
# Build configuration.
# Override NAME, PART or PROC on the command line:
#   make NAME=sdr_receiver PART=xc7z020clg400-1 all
# -----------------------------------------------------------------------------

# Solves problem with awk while building the Linux kernel.
# See: http://www.googoolia.com/wp/2015/04/21/awk-symbol-lookup-error-awk-undefined-symbol-mpfr_z_sub/
LD_LIBRARY_PATH =

NAME = led_blinker
PART = xc7z010clg400-1
PROC = ps7_cortexa9_0

VIVADO = vivado -nolog -nojournal -mode batch
XSCT   = xsct
RM     = rm -rf

# Date stamp used for generated image filenames, matches build-debian.sh convention.
DATE = $(shell date +%Y%m%d)

# -----------------------------------------------------------------------------
# Version tags for downloadable dependencies.
# Changing a tag triggers a re-download on the next make invocation.
# -----------------------------------------------------------------------------

INITRAMFS_TAG = 3.22
LINUX_TAG     = 6.12
DTREE_TAG     = xilinx_v2024.1
UBOOT_TAG     = xlnx_rebase_v2024.01_2024.1

# -----------------------------------------------------------------------------
# Derived paths -- do not edit, change the tags above instead.
# All downloaded tarballs land in tmp/ so make can track them by timestamp
# and skip redundant downloads across invocations.
# -----------------------------------------------------------------------------

INITRAMFS_DIR = tmp/initramfs-$(INITRAMFS_TAG)
LINUX_DIR     = tmp/linux-$(LINUX_TAG)
DTREE_DIR     = tmp/device-tree-xlnx-$(DTREE_TAG)

LINUX_TAR   = tmp/linux-$(LINUX_TAG).tar.xz
DTREE_TAR   = tmp/device-tree-xlnx-$(DTREE_TAG).tar.gz
RTL8188_TAR = tmp/rtl8188eu-main.tar.gz
UBOOT_TAR   = tmp/u-boot-xlnx-$(UBOOT_TAG).tar.gz

UBOOT_DIR = tmp/u-boot-xlnx-$(UBOOT_TAG)

INITRAMFS_URL = https://dl-cdn.alpinelinux.org/alpine/v$(INITRAMFS_TAG)/releases/armv7/netboot/initramfs-lts
LINUX_URL     = https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$(LINUX_TAG).52.tar.xz
DTREE_URL     = https://github.com/Xilinx/device-tree-xlnx/archive/$(DTREE_TAG).tar.gz
RTL8188_URL   = https://github.com/pavel-demin/rtl8188eu/archive/main.tar.gz
UBOOT_URL     = https://github.com/Xilinx/u-boot-xlnx/archive/$(UBOOT_TAG).tar.gz

## @brief Path to the U-Boot ELF produced by the $(UBOOT_DIR) build rule.
## @details Built automatically from Xilinx u-boot-xlnx sources on first use.
##          Preserved by clean_project and clean_projects (expensive to rebuild).
UBOOT_ELF = tmp/u-boot.elf

## @brief Per-project output directory.
PROJ_DIR = tmp/$(NAME)

## @brief List of all Verilog core sources found under cores/.
## @details $(wildcard ...) is expanded at parse time, before any rule runs,
##          so it captures the directory contents as they exist on disk.
FILES = $(shell find cores -name '*.v' -type f)
CORES = $(FILES:.v=)

FILES_SV   = $(shell find rtl -name '*.sv' -not -name '*_pkg.sv' -type f)
CORES_SV   = $(FILES_SV:.sv=)

# Prevent make from deleting intermediate files that match pattern rules.
# tmp/cores/% is included so compiled cores survive between invocations even
# though they are intermediate dependencies of the tmp/%.xpr rule.
.PRECIOUS: tmp/cores/% tmp/%.xpr tmp/%.xsa tmp/%.bit tmp/%.fsbl/executable.elf tmp/%.tree/system-top.dts

# =============================================================================
# Top-level targets
# =============================================================================

## @brief Default target. Builds bitstream, boot image, DTBs and uEnv files.
all: tmp/$(NAME).bit \
     $(PROJ_DIR)/boot.bin \
     $(PROJ_DIR)/rootfs.dtb \
     $(PROJ_DIR)/initrd.dtb \
     $(PROJ_DIR)/uEnv-rootfs.txt \
     $(PROJ_DIR)/uEnv-initrd.txt \
     zImage.bin \
     initrd.bin

## @brief Build only the FPGA bitstream (Vivado synthesis + implementation).
bit: tmp/$(NAME).bit

## @brief Build only the Vivado project file (useful for opening in the GUI).
xpr: tmp/$(NAME).xpr

## @brief Recompile only the device trees and uEnv files for the active project.
## @details This is the fast path when only DTS sources have changed.
##          Vivado, XSCT, and the kernel build are not invoked.
##          After this target completes, copy the new .dtb to the SD FAT partition.
dtb: $(PROJ_DIR)/rootfs.dtb \
     $(PROJ_DIR)/initrd.dtb \
     $(PROJ_DIR)/uEnv-rootfs.txt \
     $(PROJ_DIR)/uEnv-initrd.txt

## @brief Print the list of files to copy to the SD FAT partition for ext4 boot.
sd-rootfs: $(PROJ_DIR)/boot.bin $(PROJ_DIR)/rootfs.dtb \
           $(PROJ_DIR)/uEnv-rootfs.txt zImage.bin
	@echo ""
	@echo "=== Files to copy to SD FAT partition (rootfs boot) ==="
	@echo "  $(PROJ_DIR)/boot.bin           -> boot.bin"
	@echo "  $(PROJ_DIR)/rootfs.dtb         -> rootfs.dtb"
	@echo "  $(PROJ_DIR)/uEnv-rootfs.txt    -> uEnv.txt"
	@echo "  zImage.bin                     -> zImage.bin"
	@echo ""

## @brief Print the list of files to copy to the SD FAT partition for initrd boot.
sd-initrd: $(PROJ_DIR)/boot.bin $(PROJ_DIR)/initrd.dtb \
           $(PROJ_DIR)/uEnv-initrd.txt zImage.bin initrd.bin
	@echo ""
	@echo "=== Files to copy to SD FAT partition (initrd boot) ==="
	@echo "  $(PROJ_DIR)/boot.bin           -> boot.bin"
	@echo "  $(PROJ_DIR)/initrd.dtb         -> initrd.dtb"
	@echo "  $(PROJ_DIR)/uEnv-initrd.txt    -> uEnv.txt"
	@echo "  zImage.bin                     -> zImage.bin"
	@echo "  initrd.bin                     -> initrd.bin"
	@echo ""

## @brief Build a Debian root filesystem disk image.
##
## @details This target is intentionally separate from 'all'. It invokes
##          scripts/image.sh which calls scripts/debian.sh as root via sudo,
##          creates a 2 GiB disk image with two partitions (FAT boot + ext4
##          root), installs a Debian base system, and copies all boot files.
##
##          scripts/debian.sh expects boot-rootfs.bin in the current directory.
##          This target temporarily copies the per-project file there, calls
##          the script, then removes the temporary copy.
##
## @note    Requires sudo access. The image is written to the repo root as
##          red-pitaya-debian-13-armhf-<DATE>.img and can be flashed with dd.
##
## @par Example:
## @code
##   make NAME=led_blinker os-image
##   sudo dd if=red-pitaya-debian-13-armhf-20250320.img of=/dev/sdX bs=4M status=progress
## @endcode
os-image: $(PROJ_DIR)/boot-rootfs.bin $(PROJ_DIR)/rootfs.dtb \
         $(PROJ_DIR)/uEnv-rootfs.txt zImage.bin
	cp $(PROJ_DIR)/boot-rootfs.bin  boot-rootfs.bin
	cp $(PROJ_DIR)/rootfs.dtb       rootfs.dtb
	cp $(PROJ_DIR)/uEnv-rootfs.txt  uEnv-rootfs.txt
	sudo --preserve-env=http_proxy,https_proxy,HTTP_PROXY,HTTPS_PROXY,no_proxy,NO_PROXY \
	    sh scripts/image.sh scripts/debian.sh \
	    red-pitaya-debian-$(NAME)-13-armhf-$(DATE).img 2048
	$(RM) boot-rootfs.bin rootfs.dtb uEnv-rootfs.txt
# =============================================================================
# Download rules
# All outputs land in tmp/ so make tracks them by timestamp.
# =============================================================================

## @brief Download the Xilinx u-boot-xlnx source tarball.
$(UBOOT_TAR):
	mkdir -p $(@D)
	curl -L $(UBOOT_URL) -o $@

## @brief Extract the U-Boot source tree and apply the Red Pitaya board patch.
## @details After extraction, two modifications are made to the source tree
##          before it is considered ready for compilation:
##
##            1. patches/zynq-red-pitaya.dts is copied to arch/arm/dts/.
##               This file does not exist in upstream u-boot-xlnx; it must be
##               provided locally and describes the PS peripherals U-Boot needs
##               (UART, SD card, DDR, Ethernet).
##
##            2. The DTS filename is appended to the dtsi-list in
##               arch/arm/dts/Makefile so the U-Boot build system knows to
##               compile it into a .dtb.  Without this registration step the
##               build fails with "No rule to make target zynq-red-pitaya.dtb".
$(UBOOT_DIR): $(UBOOT_TAR)
	mkdir -p $@
	tar -zxf $< --strip-components=1 --directory=$@
	cp patches/zynq-red-pitaya.dts $@/arch/arm/dts/
	echo 'dtb-$(CONFIG_ARCH_ZYNQ) += zynq-red-pitaya.dtb' >> $@/arch/arm/dts/Makefile

## @brief Configure and compile U-Boot for Zynq-7000 (Red Pitaya).
## @details Cross-compilation requires arm-linux-gnueabihf-gcc on the host.
##          Install it with: sudo apt install gcc-arm-linux-gnueabihf
##
##          Build sequence:
##            1. xilinx_zynq_virt_defconfig  -- generates base .config for Zynq
##            2. scripts/config --set-str    -- writes the board DTS name into
##               .config as CONFIG_DEFAULT_DEVICE_TREE
##            3. olddefconfig                -- resolves any new Kconfig
##               dependencies without interactive prompts
##            4. Full build                  -- produces the u-boot ELF
$(UBOOT_ELF): $(UBOOT_DIR)
	$(MAKE) -C $< ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- xilinx_zynq_virt_defconfig
	$</scripts/config --file $</.config \
	    --set-str CONFIG_DEFAULT_DEVICE_TREE "zynq-red-pitaya"
	$(MAKE) -C $< ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig
	$(MAKE) -C $< ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$$(nproc)
	cp $</u-boot $@

$(LINUX_TAR):
	mkdir -p $(@D)
	curl -L $(LINUX_URL) -o $@

$(DTREE_TAR):
	mkdir -p $(@D)
	curl -L $(DTREE_URL) -o $@

$(RTL8188_TAR):
	mkdir -p $(@D)
	curl -L $(RTL8188_URL) -o $@

## @brief Extract and patch the Linux kernel source tree.
## @details Applies the Zynq support patch, installs the custom CMA and
##          devcfg drivers, and sets the project defconfig.
$(LINUX_DIR): $(LINUX_TAR) $(RTL8188_TAR)
	mkdir -p $@
	tar -Jxf $< --strip-components=1 --directory=$@
	mkdir -p $@/drivers/net/wireless/realtek/rtl8188eu
	tar -zxf $(RTL8188_TAR) --strip-components=1 \
	    --directory=$@/drivers/net/wireless/realtek/rtl8188eu
	patch -d tmp -p 0 < patches/linux-$(LINUX_TAG).patch
	cp patches/cma.c             $@/drivers/char
	cp patches/xilinx_devcfg.c  $@/drivers/char
	cp patches/xilinx_zynq_defconfig $@/arch/arm/configs

$(DTREE_DIR): $(DTREE_TAR)
	mkdir -p $@
	tar -zxf $< --strip-components=1 --directory=$@

## @brief Download and patch the Alpine Linux initramfs for SD card boot.
## @details The upstream image uses nlplug-findfs to discover boot media.
##          The patch replaces that with a direct mount of /dev/mmcblk0p1.
$(INITRAMFS_DIR):
	mkdir -p $@
	curl -L $(INITRAMFS_URL) | gunzip | cpio -id --directory=$@
	patch -d $@ -p 0 < patches/initramfs.patch
	rm -rf $@/etc/modprobe.d $@/lib/firmware $@/lib/modules $@/var

# =============================================================================
# Shared build outputs (kernel + initramfs)
# Identical for every project; live in the repo root; rebuilt only when
# the respective source trees change.
# =============================================================================

## @brief Compile the ARM Linux kernel image.
## @note  Takes several minutes. Output is a raw zImage for U-Boot's bootz.
zImage.bin: $(LINUX_DIR)
	make -C $< mrproper
	make -C $< ARCH=arm -j $(shell nproc 2> /dev/null || echo 1) \
	  CROSS_COMPILE=arm-linux-gnueabihf- LOADADDR=0x8000 \
	  xilinx_zynq_defconfig zImage modules
	cp $</arch/arm/boot/zImage $@

## @brief Pack the patched Alpine initramfs into a gzip-compressed CPIO archive.
## @details Padded to exactly 4 MiB so it occupies a fixed, known region in
##          RAM (0x3000000--0x33FFFFF) when loaded by U-Boot.
initrd.bin: $(INITRAMFS_DIR)
	cd $< && find . | sort | cpio -o -H newc | gzip -9 -n > ../../$@
	truncate -s 4M $@

# =============================================================================
# Per-project outputs -- all written to tmp/$(NAME)/
# =============================================================================

## @brief Generate the boot image containing only FSBL and U-Boot.
##
## @details In the original flow, boot.bin embedded the DTB, kernel, and
##          initrd alongside the bootloader, requiring a full rebuild on every
##          component change.
##
##          The current approach packages only FSBL + U-Boot. U-Boot reads
##          uEnv.txt from the FAT partition at runtime to load the kernel and
##          DTB. Modifying the device tree now only requires:
##            1. make dtb NAME=<project>   (fast, no Vivado invoked)
##            2. Copy the new .dtb to the SD card FAT partition
##
## @note    Requires $(UBOOT_ELF) to exist. See the file-level documentation.
$(PROJ_DIR)/boot.bin: tmp/$(NAME).fsbl/executable.elf $(UBOOT_ELF)
	mkdir -p $(PROJ_DIR)
	echo "img:{[bootloader] tmp/$(NAME).fsbl/executable.elf $(UBOOT_ELF)}" \
	    > $(PROJ_DIR)/boot.bif
	bootgen -image $(PROJ_DIR)/boot.bif -w -o $@

## @brief Generate the legacy boot image with embedded DTB for os-image builds.
## @details scripts/debian.sh expects this format: FSBL + U-Boot + rootfs DTB
##          pre-loaded at 0x2000000. Used exclusively by the os-image target.
$(PROJ_DIR)/boot-rootfs.bin: tmp/$(NAME).fsbl/executable.elf $(UBOOT_ELF) $(PROJ_DIR)/rootfs.dtb
	mkdir -p $(PROJ_DIR)
	echo "img:{[bootloader] tmp/$(NAME).fsbl/executable.elf $(UBOOT_ELF) [load=0x2000000] $(PROJ_DIR)/rootfs.dtb}" \
	    > $(PROJ_DIR)/boot-rootfs.bif
	bootgen -image $(PROJ_DIR)/boot-rootfs.bif -w -o $@

## @brief Compile the device tree blob for ext4 root filesystem boot.
$(PROJ_DIR)/rootfs.dtb: tmp/$(NAME).tree/system-top.dts
	mkdir -p $(PROJ_DIR)
	dtc -I dts -O dtb -o $@ -i tmp/$(NAME).tree -i dts dts/rootfs.dts

## @brief Compile the device tree blob for Alpine Linux initrd boot.
$(PROJ_DIR)/initrd.dtb: tmp/$(NAME).tree/system-top.dts
	mkdir -p $(PROJ_DIR)
	dtc -I dts -O dtb -o $@ -i tmp/$(NAME).tree -i dts dts/initrd.dts

## @brief Copy the rootfs uEnv.txt source into the per-project output directory.
## @details The source file dts/uEnv-rootfs.txt is version-controlled alongside
##          the DTS files. Edit it directly to change boot arguments or load
##          addresses; no Makefile knowledge required.
$(PROJ_DIR)/uEnv-rootfs.txt: dts/uEnv-rootfs.txt
	mkdir -p $(PROJ_DIR)
	cp $< $@

## @brief Copy the initrd uEnv.txt source into the per-project output directory.
$(PROJ_DIR)/uEnv-initrd.txt: dts/uEnv-initrd.txt
	mkdir -p $(PROJ_DIR)
	cp $< $@

# =============================================================================
# Vivado / XSCT generic pattern rules
# =============================================================================

## @brief Create a Vivado project from the block design TCL script.
## @brief Build all IP cores listed in the CORES variable.
## @details Cores are Vivado-packaged IP blocks compiled once and reused across
##          all projects. They live in tmp/cores/ and are declared as
##          prerequisites of every tmp/%.xpr rule, so they are always up to
##          date before a project is created.
##
##          To add a new core, append its name (without extension) to the CORES
##          variable and place the corresponding .v source in cores/.
##
## @par Example:
## @code
##   make cores   # build all cores without building any project
## @endcode
cores: $(addprefix tmp/, $(CORES))
cores_dev: $(addprefix tmp/cores/dev/, $(CORES_SV))

## @brief Compile a single Verilog core into a Vivado IP block.
## @details The pattern stem % matches the core name (e.g. axis_fifo).
##          The source file is taken from cores/%.v and the compiled output
##          is written to tmp/cores/%.
##          This rule is invoked automatically as a prerequisite of tmp/%.xpr;
##          you rarely need to call it directly.
tmp/cores/%: cores/%.v
	mkdir -p $(@D)
	$(VIVADO) -source scripts/core.tcl -tclargs $* $(PART)
	
tmp/cores/dev/%: rtl/%.sv
	mkdir -p $(@D)
	$(VIVADO) -source scripts/core_sv.tcl -tclargs $< $* $(PART)

## @brief Create a Vivado project from the block design TCL script.
## @details All cores in $(CORES) are compiled first (see tmp/cores/% rule).
tmp/%.xpr: projects/% $(addprefix tmp/, $(CORES))
	mkdir -p $(@D)
	$(VIVADO) -source scripts/project.tcl -tclargs $* $(PART)

## @brief Export the hardware description (.xsa) from an existing Vivado project.
tmp/%.xsa: tmp/%.xpr
	mkdir -p $(@D)
	$(VIVADO) -source scripts/hwdef.tcl -tclargs $*

## @brief Run synthesis and implementation to produce the FPGA bitstream.
tmp/%.bit: tmp/%.xpr
	mkdir -p $(@D)
	$(VIVADO) -source scripts/bitstream.tcl -tclargs $*

## @brief Generate and compile the First Stage Bootloader from the .xsa.
## @details Applies the MAC address hook so the FSBL reads the Ethernet MAC
##          from the on-board EEPROM before handing control to U-Boot.
tmp/%.fsbl/executable.elf: tmp/%.xsa
	mkdir -p $(@D)
	$(XSCT) scripts/fsbl.tcl $* $(PROC)
	cp patches/red_pitaya_fsbl_hooks.c $(@D)
	patch $(@D)/fsbl_hooks.c patches/fsbl.patch
	make -C $(@D)

## @brief Generate device tree sources from the .xsa using the Xilinx DT repo.
tmp/%.tree/system-top.dts: tmp/%.xsa $(DTREE_DIR)
	mkdir -p $(@D)
	$(XSCT) scripts/devicetree.tcl $* $(PROC) $(DTREE_DIR)
	sed -i 's|#include|/include/|' $@

## @brief Export block design TCL from an open project (after GUI edits)
export-bd: tmp/$(NAME).xpr
	$(VIVADO) -source scripts/export_bd.tcl -tclargs $(NAME)
	
# =============================================================================
# Cleanup
# =============================================================================

## @brief Remove ALL generated files, including shared kernel and tarballs.
## @details Use this for a completely fresh build. Deletes tmp/ entirely as
##          well as zImage.bin and initrd.bin from the repo root.
##          After this, the next 'make all' will re-download all dependencies
##          and recompile the kernel from scratch.
clean:
	$(RM) zImage.bin initrd.bin tmp
	$(RM) .Xil usage_statistics_webtalk.html usage_statistics_webtalk.xml
	$(RM) vivado*.jou vivado*.log
	$(RM) webtalk*.jou webtalk*.log

## @brief Remove build artifacts for the project specified by NAME only.
## @details Preserves all shared artifacts: kernel, initramfs, tarballs,
##          u-boot.elf, device-tree generator, and compiled IP cores
##          (tmp/cores/) since those are shared across all projects.
##          The next 'make all' for this project will re-run Vivado, XSCT,
##          and dtc, but will skip cores that are already compiled.
##
## @par Example:
## @code
##   make clean_project NAME=sdr_receiver
## @endcode
clean_project:
	$(RM) tmp/$(NAME).xpr
	$(RM) tmp/$(NAME).xsa
	$(RM) tmp/$(NAME).bit
	$(RM) tmp/$(NAME).cache
	$(RM) tmp/$(NAME).gen
	$(RM) tmp/$(NAME).hw
	$(RM) tmp/$(NAME).ip_user_files
	$(RM) tmp/$(NAME).runs
	$(RM) tmp/$(NAME).sim
	$(RM) tmp/$(NAME).srcs
	$(RM) tmp/$(NAME).fsbl
	$(RM) tmp/$(NAME).tree
	$(RM) tmp/$(NAME)

## @brief Remove build artifacts for ALL projects while keeping shared files.
## @details The following artifacts are preserved because they are shared
##          across all projects and expensive to rebuild:
##            - zImage.bin, initrd.bin (compiled kernel and initramfs)
##            - tmp/cores/                       (compiled IP cores)
##            - tmp/linux-$(LINUX_TAG)/          (kernel source tree)
##            - tmp/initramfs-$(INITRAMFS_TAG)/  (initramfs source)
##            - tmp/device-tree-xlnx-$(DTREE_TAG)/
##            - tmp/*.tar.xz, tmp/*.tar.gz       (downloaded tarballs)
##            - tmp/u-boot.elf
##
##          Everything else in tmp/ -- Vivado projects, bitstreams, FSBLs,
##          device tree outputs, and per-project output directories -- is
##          deleted regardless of which project generated it.
##
##          This is useful for freeing disk space after building many projects
##          without losing the expensive shared build artifacts.
clean_projects:
	# Remove all Vivado-generated top-level files (.xpr, .xsa, .bit).
	find tmp -maxdepth 1 \
	    \( -name '*.xpr' -o -name '*.xsa' -o -name '*.bit' \) \
	    -exec $(RM) {} +
	# Remove all project-specific directories: anything under tmp/ that is
	# not one of the known shared source trees, downloaded tarballs, or cores.
	find tmp -maxdepth 1 -mindepth 1 -type d \
	    ! -name 'cores' \
	    ! -name 'linux-$(LINUX_TAG)' \
	    ! -name 'initramfs-$(INITRAMFS_TAG)' \
	    ! -name 'device-tree-xlnx-$(DTREE_TAG)' \
	    ! -name 'u-boot-xlnx-$(UBOOT_TAG)' \
	    -exec $(RM) -rf {} +
	    

