# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gpio_0_0/system_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gpio_0_0 || ORIG_REF_NAME==system_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hub_0_0/system_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hub_0_0 || ORIG_REF_NAME==system_hub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_0/system_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_0 || ORIG_REF_NAME==system_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_0/system_slice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_0 || ORIG_REF_NAME==system_slice_4_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_0/system_slice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_0 || ORIG_REF_NAME==system_slice_5_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_0/system_slice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_0 || ORIG_REF_NAME==system_slice_6_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_7_0/system_slice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_7_0 || ORIG_REF_NAME==system_slice_7_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_8_0/system_slice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_8_0 || ORIG_REF_NAME==system_slice_8_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_0/system_bcast_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_0 || ORIG_REF_NAME==system_bcast_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_0/system_rate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_0 || ORIG_REF_NAME==system_rate_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_0/system_rate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_0 || ORIG_REF_NAME==system_rate_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_0/system_cic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_0 || ORIG_REF_NAME==system_cic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_0/system_cic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_0 || ORIG_REF_NAME==system_cic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_0/system_comb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_0 || ORIG_REF_NAME==system_comb_0_0} -quiet] -quiet

# IP: bd/system/ip/system_trig_0_0/system_trig_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_trig_0_0 || ORIG_REF_NAME==system_trig_0_0} -quiet] -quiet

# IP: bd/system/ip/system_scope_0_0/system_scope_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scope_0_0 || ORIG_REF_NAME==system_scope_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_1_0/system_const_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_1_0 || ORIG_REF_NAME==system_const_1_0} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_0/system_writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_writer_0_0 || ORIG_REF_NAME==system_writer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_0_0/system_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_0_0 || ORIG_REF_NAME==system_concat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_trigger_0_0/system_axis_trigger_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_trigger_0_0 || ORIG_REF_NAME==system_axis_trigger_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_broadcaster_1_0/system_axis_broadcaster_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_broadcaster_1_0 || ORIG_REF_NAME==system_axis_broadcaster_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_broadcaster_2_0/system_axis_broadcaster_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_broadcaster_2_0 || ORIG_REF_NAME==system_axis_broadcaster_2_0} -quiet] -quiet

# IP: bd/system/ip/system_or_gate_0_0/system_or_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_or_gate_0_0 || ORIG_REF_NAME==system_or_gate_0_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_1/system_comb_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_1 || ORIG_REF_NAME==system_comb_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_counter_0_0/system_axis_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_counter_0_0 || ORIG_REF_NAME==system_axis_counter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_2_0/system_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_2_0 || ORIG_REF_NAME==system_xlconstant_2_0} -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_bcast_0_0/system_bcast_0_0_ooc.xdc

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_axis_broadcaster_1_0/system_axis_broadcaster_1_0_ooc.xdc

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/ip/system_axis_broadcaster_2_0/system_axis_broadcaster_2_0_ooc.xdc

# XDC: /home/lorenzo/PI/red-pitaya-notes/projects/trigger_interrupts/trigger_interrupts.gen/sources_1/bd/system/system_ooc.xdc
